---
title: "Publications"
---

[Social media and Morality](https://psyarxiv.com/ywevq/) <br>
with [Jay Van Bavel](https://www.jayvanbavel.com/), [Claire Robertson](https://scholar.google.com/citations?user=U86vr3EAAAAJ&hl=en&oi=ao), Kareena del Rosario, [Steve Rathje](https://stevenrathje.com/) <br>
Forthcoming in Annual Review of Psychology


[Individual-level solutions may support system-level change – if they are internalized as part of one’s social identity](https://psyarxiv.com/3qvpb) <br>
with [Lina Koppel](https://scholar.google.se/citations?user=hfioc6YAAAAJ&hl=sv), [Claire Robertson](https://scholar.google.com/citations?user=U86vr3EAAAAJ&hl=en&oi=ao), [Kim E. Doell](https://www.kimdoell.com/), [Ali Javeed](https://www.alijaveed.com/), [Steve Rathje](https://stevenrathje.com/), [Madalina Vlasceanu](https://www.mvlasceanu.com/), and [Jay Van Bavel](https://www.jayvanbavel.com/) <br>
Forthcoming in Behavioral and Brain Sciences

[Addressing Online Political Hostility](https://politica.dk/fileadmin/politica/Dokumenter/Afhandlinger/jesper_rasmussen.pdf) <br>
PhD Dissertation, 2023

[Andresen, M. J., Karg, S. T. S., Rasmussen, S. H. R., Pradella, L., **Rasmussen, J.**, Lindekilde, L., & Petersen, M. B. (2022)](https://pure.au.dk/portal/files/271291115/Danskernes_oplevelse_af_had_pa_de_sociale_medier_Rapport_Aarhus_Universitet_.pdf). Danskernes oplevelse af had på sociale medier. (English title: "The Danes' experiences of hate on social media")

[Lindekilde, L. and **Rasmussen, J.** (2022)](https://tidsskrift.dk/politica/article/view/132523/177705) ‘Had, humor og bystander-reaktioner: danske unges reaktioner på politisk hadefulde memes’, Politica, 54(2), pp. 170–203. doi:10.7146/politica.v54i2.132523. (English title: "Hate, humor and by-stander-reactions: Danish Youth's reaction to hateful political memes").

[Lieberoth, A., Lin, S.-Y., Stöckli, S., Han, H., Kowal, M., Gelpi, R., Chrona, S., Tran, T. P., Jeftić, A., **Rasmussen, J.**, Cakal, H., & Milfont, T. L. (2021).](https://doi.org/10.1098/rsos.200589) Stress and worry in the 2020 coronavirus pandemic: Relationships to trust and compliance with preventive measures across 48 countries in the COVIDiSTRESS global survey. Royal Society Open Science, 8(2), 200589. 

[Yamada, Y., Ćepulić, D.-B., Coll-Martín, T., Debove, S., Gautreau, G., Han, H., **Rasmussen, J.**, Tran, T. P., Travaglino, G. A., & Lieberoth, A. (2021).](https://doi.org/10.1038/s41597-020-00784-9) COVIDiSTRESS Global Survey dataset on psychological and behavioural consequences of the COVID-19 outbreak. Scientific Data, 8(1), 3. 

[Kowal, M., Coll‐Martín, T., Ikizer, G., **Rasmussen, J.**, Eichel, K., Studzińska, A., Koszałkowska, K., Karwowski, M., Najmussaqib, A., Pankowski, D., Lieberoth, A., & Ahmed, O. (2020).](https://doi.org/10.1111/aphw.12234) Who is the most stressed during the COVID‐19 pandemic? Data from 26 countries and areas. Applied Psychology: Health and Well-Being. - 

[Ikizer, G., Kowal, M., Aldemir, İ. D., Jeftić, A., Memisoglu-Sanli, A., Najmussaqib, A., Lacko, D., Eichel, K., Turk, F., Chrona, S., Ahmed, O., **Rasmussen, J.**, Kumaga, R., Uddin, M. K., Reynoso-Alcántara, V., Pankowski, D., & Coll-Martín, T. (2022).](https://doi.org/10.1016/j.paid.2022.111531) Big Five traits predict stress and loneliness during the COVID-19 pandemic: Evidence for the role of neuroticism. Personality and Individual Differences, 190, 111531.

## Working papers 


[**Rasmussen, J.**, (under review)](https://psyarxiv.com/856z9/) Anti-Egalitarian Values Predict Opposition to Hate Speech Restrictions

[**Rasmussen, J.**, (under review)](https://psyarxiv.com/r3y5u/) Ventilators, Colliders and Megaphones: Pathways To Online Political Hostility On Social Media

Karg, Simon Tobias; Hansen, Tanja Marie; Lindekilde, Lasse; **Rasmussen, Jesper** (in prep). Drivers of intentions to engage in prosocial bystander reactions - [Preregistration](https://osf.io/bpmy3/)

[**Rasmussen Jesper** (under review)](https://psyarxiv.com/j4nuc/). When Do the Public Support Hate Speech Restrictions? Symmetries and Asymmetries across Partisans in Denmark and the United States - [Pre-registration](https://osf.io/7xvq6/)

[**Rasmussen, Jesper**.; Lindekilde, Lasse; Petersen, Michael Bang, (revise and resubmit)](https://psyarxiv.com/8wdfp). Public health communication decreases false headline sharing by boosting self-efficacy - [Pre-registration](https://osf.io/3v6qk/)


[Marie, A; Rasmussen, J; Osmundsen, M; Petersen, M.B., (n.d.). Audience, anonymity and hostile rumour sharing](https://osf.io/haq72)
